//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ODIN.rc
//
#define ID_BT_VERIFY                    3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_VOLUME_INFO                 129
#define IDS_VOLUME_NOSEL                130
#define IDS_CANTREADFILE                131
#define IDS_CANTWRITEFILE               132
#define IDS_NOTENOUGHSPACE              133
#define IDS_WARNING                     134
#define IDS_ERROR                       135
#define IDS_IMAGETOOBIG                 136
#define IDS_IMAGETOOSMALL               137
#define IDS_WRONGFILEFORMAT             138
#define IDS_BROWSE                      139
#define IDS_CANNOTOPENFILE              140
#define IDS_HEADERTEMPLATE              141
#define IDS_PROVIDE_FILENAME            142
#define IDS_VERIFY_TITLE                143
#define IDS_VERIFY_OK                   144
#define IDS_VERIFY_FAILED               145
#define IDS_FILE_EXISTS                 146
#define IDS_ERASE_DRIVE                 147
#define IDS_LICENSEFILEMISSING          148
#define IDS_ENTERCOMMENT                149
#define IDS_FILEDESCR                   150
#define IDS_DEFAULTEXT                  151
#define IDS_CANNOTDELETEFILE            152
#define IDS_NOTSAMEDRIVE                153
#define IDS_NOWINDIRBACKUP              154
#define IDS_NORESTORETOWINDOWS          155
#define IDS_WRONGPARTITIONTYPE          156
#define IDS_4GBLIMITEXCEEDED            157
#define IDS_SPLITSIZETOOSMALL           158
#define IDS_CANCEL                      159
#define IDS_EXIT                        160
#define IDS_CONFIRMCANCEL               161
#define IDS_FILTERSTRING                162
#define IDS_ASK_DELETE_FILES            163
#define IDS_ASK_CONTINUE                164
#define IDS_DRIVE                       165
#define IDS_SIZE                        166
#define IDS_NAME                        167
#define IDS_TYPE                        168
#define IDS_VOLNAME                     169
#define IDS_VERSION_32_BIT              170
#define IDS_VERSION_64_BIT              171
#define IDD_DIALOG_SETTINGS             201
#define IDD_ODIN_MAIN                   202
#define IDD_OPTIONS                     204
#define ID_DIALOG_SPLASH                205
#define IDD_DIALOG_SPLASH               205
#define IDS_INCOMPLETE_IMAGE            206
#define IDS_UNMOUNTED_VOLUME            207
#define IDC_LABEL_BYTES_TOTAL           1009
#define IDC_TAB_GENERAL                 1010
#define IDC_TABS_SETTINGS               1011
#define IDC_LABEL_BYTES_PROCESSED       1012
#define IDC_LABEL_SPEED                 1013
#define IDC_LABEL_TIME_ELAPSED          1014
#define IDC_LABEL_TIME_LEFT             1015
#define IDC_LABEL_PERCENT               1016
#define IDC_RADIO_BACKUP                1018
#define IDC_RADIO_RESTORE               1019
#define IDC_LIST_VOLUMES                1020
#define IDC_COMBO_FILES                 1021
#define IDC_TEXT_VOLUME                 1022
#define IDC_TEXT_FILE                   1023
#define IDC_VERNO                       1024
#define IDC_TEXT_VOLUME2                1025
#define IDC_GROUP_DISKVOL               1026
#define IDC_GROUP_FILE                  1027
#define IDC_PROGRESS_PERCENT            1028
#define IDC_BT_USED_BLOCKS              1032
#define IDC_BT_ALL_BLOCKS               1033
#define IDC_BT_NO_COMPRESSION           1034
#define IDC_BT_COMPRESSION_GZIP         1035
#define IDC_BT_COMPRESSION_BZIP2        1036
#define IDC_BT_NO_SPLIT                 1037
#define IDC_BT_SPLIT_CHUNK              1038
#define IDC_ED_CHUNK_SIZE               1039
#define IDC_PLATFORM                    1040
#define IDC_STATIC_MESSAGE              1041
#define IDC_CHECK_NOTDISPLAYAGAIN       1042
#define IDC_EDIT_MESSAGE                1044
#define IDC_BUTTON_LICENSE              1045
#define IDC_EDIT_FILE                   1046
#define IDC_CREDITS                     1047
#define IDC_HYPER                       1048
#define IDC_BT_SNAPSHOT                 1052
#define IDS_ERRCMDLINE_NO_OPERATION     57346
#define IDS_ERRCMDLINE_UNKNOWN_OPTION   57347
#define IDS_ERRCMDLINE_USAGE            57348
#define IDS_ERRCMDLINE_WRONG_COMPRESSION 57349
#define IDS_ERRCMDLINE_NO_TARGET        57350
#define IDS_ERRCMDLINE_NO_SOURCE        57351
#define IDS_ERRCMDLINE_WRONG_SOURCE     57352
#define IDS_ERRCMDLINE_WRONG_TARGET     57353
#define IDS_ERRCMDLINE_WRONG_INDEX      57354
#define IDS_ERRCMDLINE_BACKUP_PARAM_ERROR 57355
#define IDS_ERRCMDLINE_RESTORE_PARAM_ERROR 57356
#define IDS_ERRCMDLINE_VERIFY_PARAM_ERROR 57357
#define ID_BT_OPTIONS                   57665
#define ID_BT_BROWSE                    57666
#define IDS_PARTITION_FAT12             61403
#define IDS_PARTITION_FAT16             61404
#define IDS_PARTITION_FAT32             61405
#define IDS_PARTITION_NTFS              61406
#define IDS_PARTITION_UNKNOWN           61407
#define IDS_DRIVE_TYPE_FIXED            61408
#define IDS_DRIVE_TYPE_REMOVABLE        61409
#define IDS_DRIVE_TYPE_FLOPPY           61410
#define IDS_DRIVE_TYPE_UNKNOWN          61411
#define IDS_WAITUPDATEDRIVES            61412
#define IDS_DIALOGTITLE                 61413
#define IDS_STATUS_OPERATION_COMPLETED  61414
#define IDS_STATUS_OPERATION_CANCELLED  61415
#define IDS_STATUS_BACKUP_PARTITION_PROGRESS 61416
#define IDS_STATUS_RESTORE_PARTITION_PROGRESS 61417
#define IDS_STATUS_BACKUP_DISK_PROGRESS 61418
#define IDS_STATUS_RESTORE_DISK_PROGRESS 61419
#define IDS_STATUS_VERIFY_PROGRESS      61420
#define IDS_STATUS_RESTORE_MBR_PROGRESS 61421
#define IDS_STATUS_TAKE_SNAPSHOT        61422

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
